version: '3.1'

services:
  db:
    image: mariadb:5
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - ./data:/var/lib/mysql
  genesis:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    depends_on:
      - db
